// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBikyhGilDl14chAFDkkEZDSkRTfP10NdY',
    appId: '1:607235190607:web:04f51523bc4eca06695f3a',
    messagingSenderId: '607235190607',
    projectId: 'minimal-social-app-e4080',
    authDomain: 'minimal-social-app-e4080.firebaseapp.com',
    storageBucket: 'minimal-social-app-e4080.appspot.com',
    measurementId: 'G-6BXL0TN7ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYe9oj-rvPpGbIssZrnwMwaorLwHHAYN8',
    appId: '1:607235190607:android:38d9523b8842ebb0695f3a',
    messagingSenderId: '607235190607',
    projectId: 'minimal-social-app-e4080',
    storageBucket: 'minimal-social-app-e4080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqrHyxYv-JSzsrUPgH2n1osJVqmp97Qdo',
    appId: '1:607235190607:ios:3582b94d99d1a4c8695f3a',
    messagingSenderId: '607235190607',
    projectId: 'minimal-social-app-e4080',
    storageBucket: 'minimal-social-app-e4080.appspot.com',
    iosBundleId: 'com.example.minimalsocialture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqrHyxYv-JSzsrUPgH2n1osJVqmp97Qdo',
    appId: '1:607235190607:ios:3582b94d99d1a4c8695f3a',
    messagingSenderId: '607235190607',
    projectId: 'minimal-social-app-e4080',
    storageBucket: 'minimal-social-app-e4080.appspot.com',
    iosBundleId: 'com.example.minimalsocialture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBikyhGilDl14chAFDkkEZDSkRTfP10NdY',
    appId: '1:607235190607:web:2b8c01ebd61b7ff1695f3a',
    messagingSenderId: '607235190607',
    projectId: 'minimal-social-app-e4080',
    authDomain: 'minimal-social-app-e4080.firebaseapp.com',
    storageBucket: 'minimal-social-app-e4080.appspot.com',
    measurementId: 'G-4PV7EHC0J2',
  );
}
